MVCEgitim/Controllers/MVC01RazorSyntaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEgitim.Controllers
{
    public class MVC01RazorSyntaxController : Controller
    {
        // GET: MVC01RazorSyntax
        public ActionResult Index() // bir action a view eklemek için Index() ismine sağ tık add view diyerek açılan pencereden isim verip ekleyebiliriz veya direk views klasörüne sağ tık diyerek de ekleyebiliriz.
        {
            return View();
        }
    }
}

MVCEgitim/Controllers/MVC02HtmlHelpersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEgitim.Controllers
{
    public class MVC02HtmlHelpersController : Controller
    {
        // GET: MVC02HtmlHelpers
        public ActionResult Index()
        {
            return View();
        }
    }
}

MVCEgitim/Controllers/MVC03DataTransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCEgitim.Controllers
{
    public class MVC03DataTransferController : Controller
    {
        // GET: MVC03DataTransfer
        public ActionResult Index(string kelime, string fiyat) // get metoduyla query string üzerinden gönderilen veriyi bu şekilde parantez içine yazarak yakalayabiliriz. Burada önemli nokta form içerisindeki inputlara verdiğimiz name(isim) değeri neyse o isimle dilediğimiz kadar alan ekleyebiliriz.
        {
            // MVC de 3 temel yöntemle view a veri gönderebiliriz
            // 1- Viewbag
            ViewBag.UrunKategorisi = "Bilgisayar";
            // 2- Viewdata
            ViewData["UrunAdi"] = "Casper Monitör";
            // 3- TempData
            TempData["UrunFiyati"] = 99.90;

            ViewBag.Kelime = kelime;
            ViewBag.Fiyat = fiyat;
            return View();
        }
        [HttpPost] // aşağıdaki index metodunun sayfadaki post işleminden sonra çalışması gerektiğini bu attribute ile belirtiyoruz
        public ActionResult Index(string text1, string ddlListe, bool cbOnay, FormCollection formCollection) // formCollection nesnesi ekrandaki form elementi içerisindeki alanlara ulaşmamızı sağlar
        {
            // 1. Yöntem parametrelerden gelen veriler
            ViewBag.Mesaj = "textbox dan gelen veri : " + text1;
            ViewBag.MesajListe = "dropdownlist den gelen veri : " + ddlListe;
            TempData["Tdata"] = "checkbox dan seçilen değer : " + cbOnay;

            // 2. Yöntem formCollection dan gelen veriler
            ViewBag.Mesaj2 = "textbox dan gelen veri : " + formCollection["text1"];
            ViewBag.MesajListe2 = "dropdownlist den gelen veri : " + formCollection["ddlListe"];
            TempData["Tdata2"] = "checkbox dan seçilen değer : " + formCollection.GetValues("cbOnay")[0]; // checkbox için

            // 3. Yöntem Request Form dan gelen veriler
            ViewBag.Mesaj3 = "textbox dan gelen veri : " + Request.Form["text1"];
            ViewBag.MesajListe3 = "dropdownlist den gelen veri : " + Request.Form["ddlListe"];
            TempData["Tdata3"] = "checkbox dan seçilen değer : " + Request.Form.GetValues("cbOnay")[0]; // checkbox için
            return View();
        }
    }
}

MVCEgitim/Views/Shared/KategorileriModelleGetir.cshtml
@model List<string>

<ul class="list-group">
    @foreach (var item in Model)
    {
        <li>
            <a href="/MVC08ViewResults?kategori=@item" class="nav-link">@item</a>
        </li>
    }
</ul>

MVCEgitim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("ozelcss", required: false)
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container-fluid">
            @Html.ActionLink("MVC Eğitim", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Anasayfa", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("RazorSyntax", "Index", "MVC01RazorSyntax", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("HtmlHelpers", "Index", "MVC02HtmlHelpers", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("DataTransfer", "Index", "MVC03DataTransfer", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>
                        @*burası MVC yorum satırı*@
                        <a href="/MVC04ModelBinding" class="nav-link">ModelBinding</a>
                    </li>
                    @Html.Partial("_PartialMenu")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
        @RenderSection("ozelicerik", required: false)
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVCEgitim/Views/Shared/_PartialMenu.cshtml
<li>
    <a href="/MVC05ModelValidation" class="nav-link">ModelValidation</a>
</li>
<li>
    <a href="/MVC06Section" class="nav-link">Section</a>
</li>
<li>
    <a href="/MVC07Partial" class="nav-link">Partial</a>
</li>
<li>
    <a href="/MVC08ViewResults" class="nav-link">ViewResults</a>
</li>
<li>
    <a href="/MVC09FileUpload" class="nav-link">FileUpload</a>
</li>

<div class="dropdown">
    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">

        Dropdown link
    </a>
    Diğer Konular
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="/MVC10Cookie">MVC Cookies</a></li>
        <li><a class="dropdown-item" href="/MVC11Session">MVC Session</a></li>
        <li><a class="dropdown-item" href="/MVC12StringFormat">String Formatlama</a></li>
        <li><a class="dropdown-item" href="/MVC13AppSetting">App Setting</a></li>
        <li><a class="dropdown-item" href="/MVC14Filters">Filters Kullanımı</a></li>
    </ul>
</div>